### ISSUE TITLE
ncnn转换后，是否应该启用角度分类模型

### ISSUE THREAD

**Issue by lfstrong** [benjaminwan/RapidOCRNcnnCpp#4]
我转换好角度分类模型启用后，反而识别是乱码了，不启用是正常的，我看readme上说倒置图片才要启用，但是没有角度分类的话，怎么知道图片是不是倒置了。

**Comment by benjaminwan** [comment]
https://github.com/benjaminwan/RapidOCRNcnnCpp/releases/tag/init
这里有提供转换好的cls模型
https://github.com/benjaminwan/RapidOCRNcnnCpp/releases/download/init/models_20210408-2.7z

--doAngle 1 这个选项打开后，我试了倒置180度的图片是可以正常识别的。

你自己转换的模型，如果转换工具有输出任何警告信息，就是转换失败了。
不要觉得生成了模型文件就是转换成功了，onnx2ncnn这个工具不论成功失败都会生成模型文件。

**Comment by lfstrong** [comment]
好的，就直接用qq群里的c++代码就可以了吧，没有换吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "benjamin ***@***.***&gt;; 
发送时间: 2022年8月2日(星期二) 上午8:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [benjaminwan/RapidOCRNcnnCpp] ncnn转换后，是否应该启用角度分类模型 (Issue #4)





 
https://github.com/benjaminwan/RapidOCRNcnnCpp/releases/tag/init
 这里有提供转换好的cls模型
 https://github.com/benjaminwan/RapidOCRNcnnCpp/releases/download/init/models_20210408-2.7z
 
--doAngle 1 这个选项打开后，我试了倒置180度的图片是可以正常识别的。
 
你自己转换的模型，如果转换工具有输出任何警告信息，就是转换失败了。
 不要觉得生成了模型文件就是转换成功了，onnx2ncnn这个工具不论成功失败都会生成模型文件。

**Comment by benjaminwan** [comment]
代码没有改

**Comment by lfstrong** [comment]
好的谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "benjamin ***@***.***&gt;; 
发送时间: 2022年8月2日(星期二) 上午9:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [benjaminwan/RapidOCRNcnnCpp] ncnn转换后，是否应该启用角度分类模型 (Issue #4)





 
代码没有改
